{{ if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "headband.fullname" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "headband.labels" . | nindent 4 }}
    app: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.backend.service.metricsPort }}
      targetPort: {{ .Values.backend.service.metricsPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "headband.selectorLabels" . | nindent 4 }}
    app: backend
{{ end }}
