GRANT CONNECT ON DATABASE headband_db TO headband;
GRANT USAGE ON SCHEMA public TO headband;
GRANT ALL PRIVILEGES ON SCHEMA public TO headband;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO headband;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO headband;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO headband;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO headband;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO headband;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO headband;
